############################
## CHANGE THESE
############################

baseURL: "https://VasylPosmit.github.io/vp"
title: Vasyl Posmit

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: false
