############################
## CHANGE THESE
############################

baseURL: "https://vasylposmit.com/"
title: Vasyl Posmit

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: false
