############################
## Navbar
############################

main:
- name: Contact
  url: /
  weight: 10
- name: Content
  url: /writing/
  weight: 20
- name: About
  url: /about/
  weight: 30