############################
## Author
############################

author:
  name: Vasyl Posmit
  image: author.png
  greeting: "Welcome to my personal site where I share my thoughts :sparkles:\n\n You are welcome to reach out to me on any of the platforms below."
  icon: ":wave:"

############################
## Links
############################

links:
  - github: https://github.com/VasylPosmit
  - link: https://github.com/VasylPosmit/vp#readme
  - linkedin: https://www.linkedin.com/in/posmit/
  - telegram:  https://t.me/posmit
  # - email: vasyl.posmit@gmail.com
  # - website: 
  # - x-twitter: 
  # - mastodon: 
  # - instagram: 
  # - reddit: 
  # - whatsapp: 
  # - signal: 
  # - codepen: 
  # - dev: 
  # - discord: 
  # - orcid: 
  # - slack: 
  # - stack-overflow: 
  # - twitch: 
  # - patreon: 
  # - soundcloud: 
  # - dribbble: 
  # - stack-exchange: 
  # - tiktok: 
  # - youtube: 
  # - keybase: 
  # - flickr: 
  # - tumblr: 
  # - kickstarter: 
  # - snapchat:
  # - bluesky: 
  # - bitbucket: 
  # - bandcamp: 
  # - etsy: 
  # - spotify: 
  # - pinterest: 
  # - strava: 
  # - untappd: 
  # - skype: 
  # - medium: 
  # - foursquare: 
  # - apple: 
  # - amazon:
  # - google:
  # - paypal:
  # - windows:

###############################
## OpenGraph & Twitter Cards
###############################

title: paramsVasyl
description: "description: Site build with Qubt & Hugo"
images:
  - thumbnail.png
